(function(){
  const A=window.LumenAuth;
  const $=s=>document.querySelector(s);
  let user=null;
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function open(html){$('#modal').classList.remove('hidden');$('#modalContent').innerHTML=html}
  function config(){open(`<h2>ربط الحساب</h2><p class="muted">اربط Lumen بمشروع Supabase بتاعك. استخدم Project URL و Publishable/Anon Key فقط — ممنوع Service Role Key هنا.</p><label>Supabase Project URL<input id="sbUrl" class="accountInput" placeholder="https://xxxx.supabase.co"></label><label>Publishable / Anon Key<input id="sbKey" class="accountInput" placeholder="sb_publishable_... أو المفتاح العام"></label><button class="buy" id="saveSb">حفظ وربط الحساب</button>`);$('#saveSb').onclick=()=>{const u=$('#sbUrl').value,k=$('#sbKey').value;if(!u||!k)return alert('اكتب الرابط والمفتاح العام.');A.save(u,k)}}
  async function sync(){if(!A.client||!user)return;const {data,error}=await A.client.from('wishlists').select('game_id');if(error)return;const ids=(data||[]).map(x=>String(x.game_id));localStorage.setItem('lumen:favs',JSON.stringify(ids));location.reload()}
  async function addWish(id){if(!A.client||!user)return;try{const j=await fetch('/api/game?id='+encodeURIComponent(id)).then(r=>r.json()),i=j.game?.info||{};await A.client.from('wishlists').upsert({user_id:user.id,game_id:String(id),title:i.title||'',thumb:i.thumb||'',steam_app_id:i.steamAppID?String(i.steamAppID):null},{onConflict:'user_id,game_id'})}catch(e){console.warn(e)}}
  async function removeWish(id){if(!A.client||!user)return;await A.client.from('wishlists').delete().eq('user_id',user.id).eq('game_id',String(id))}
  async function social(provider,label){try{const r=await A.login(provider);if(r?.error)alert(`تعذر الدخول بـ ${label}: ${r.error.message}`)}catch(e){alert(`تعذر الدخول بـ ${label}. تأكد أن Provider مفعّل في Supabase.`)}}
  function loginUI(){open(`<h2>◉ تسجيل الدخول إلى Lumen</h2><p class="muted">اختار الطريقة اللي تناسبك. لازم تفعيل الـ Provider من Supabase مرة واحدة.</p><div class="socialGrid"><button class="socialBtn" data-provider="google">G Google</button><button class="socialBtn" data-provider="github">● GitHub</button><button class="socialBtn" data-provider="discord">◉ Discord</button><button class="socialBtn" data-provider="azure">▣ Microsoft</button></div><button class="buy secondaryBtn" id="changeConfig">⚙ ربط/تغيير Supabase</button>`);document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>social(b.dataset.provider,b.textContent.trim()));$('#changeConfig').onclick=config}
  async function account(){if(!A.client)return config();user=await A.user();if(!user)return loginUI();open(`<h2>◉ حسابي</h2><p><b>${esc(user.user_metadata?.full_name||user.email||'مستخدم Lumen')}</b></p><p class="muted">المفضلة والتنبيهات متزامنة مع حسابك.</p><button class="buy" id="alertsList">🔔 تنبيهات الأسعار</button><button class="buy" id="logout">تسجيل الخروج</button>`);$('#logout').onclick=async()=>{await A.logout();location.reload()};$('#alertsList').onclick=alerts}
  async function alerts(){if(!user)return account();const {data}=await A.client.from('price_alerts').select('*').eq('user_id',user.id).eq('active',true).order('created_at',{ascending:false});open(`<h2>🔔 تنبيهات الأسعار</h2>`+((data||[]).map(x=>`<div class="offer"><div><b>${esc(x.title||'Game')}</b><small>تنبيه عند ${Number(x.target_egp).toLocaleString('en-US')} ج.م</small></div><button class="buy" data-del-alert="${x.id}">حذف</button></div>`).join('')||'<p>مفيش تنبيهات محفوظة.</p>'));document.querySelectorAll('[data-del-alert]').forEach(b=>b.onclick=async()=>{await A.client.from('price_alerts').delete().eq('id',b.dataset.delAlert).eq('user_id',user.id);alerts()})}
  async function saveAlert(id,title){if(!A.client||!user){account();return}const target=prompt('اكتب السعر المستهدف بالجنيه المصري:', '1000');if(!target||Number(target)<=0)return;const {error}=await A.client.from('price_alerts').upsert({user_id:user.id,game_id:String(id),title:String(title||'Game'),target_egp:Number(target),active:true},{onConflict:'user_id,game_id'});if(error)alert('تعذر حفظ التنبيه. تأكد إنك شغلت supabase_schema.sql.');else alert('تم حفظ تنبيه السعر 🔔')}
  document.addEventListener('click',async e=>{const fav=e.target.closest('[data-fav]');if(fav){const id=String(fav.dataset.fav);if(A.client&&user){const exists=JSON.parse(localStorage.getItem('lumen:favs')||'[]').includes(id);setTimeout(()=>exists?removeWish(id):addWish(id),50)}}const al=e.target.closest('[data-alert]');if(al){e.preventDefault();e.stopImmediatePropagation();await saveAlert(al.dataset.alert,document.querySelector('.gameHero h2')?.textContent)}},true);
  async function boot(){if(!A)return;await A.init();user=await A.user();if(user)await sync();$('#accountBtn').onclick=account;$('#accountDrawer').onclick=()=>{account();$('#drawer').classList.add('hidden')};$('#alertsBtn').onclick=()=>{alerts();$('#drawer').classList.add('hidden')};}
  boot();
})();
