const $=s=>document.querySelector(s);const state={deals:[],sort:'DealRating',fx:51};const stores={'1':'Steam','2':'GamersGate','3':'GreenManGaming','4':'Amazon','5':'GameStop','6':'Direct2Drive'};const software=[['Adobe Photoshop','تصميم وتحرير الصور','https://www.adobe.com/products/photoshop.html'],['Microsoft 365','Office + خدمات Microsoft','https://www.microsoft.com/microsoft-365'],['Office Home 2024','Office للكمبيوتر','https://www.microsoft.com/microsoft-365/p/office-home-2024'],['Canva Pro','تصميم ومحتوى','https://www.canva.com/pro/'],['JetBrains','أدوات البرمجة','https://www.jetbrains.com/'],['Windows 11','نظام التشغيل','https://www.microsoft.com/software-download/windows11']];
function egp(n){return Math.round(Number(n||0)*state.fx).toLocaleString('en-US')+' ج.م'}function storeUrl(d){if(d.steamAppID)return `https://store.steampowered.com/app/${d.steamAppID}/?cc=eg`;const q=encodeURIComponent(d.title||'game');const id=String(d.storeID);if(id==='3')return `https://www.greenmangaming.com/search/?query=${q}`;if(id==='2')return `https://www.gamersgate.com/search?q=${q}`;if(id==='4')return `https://www.amazon.com/s?k=${q}+pc+game`;if(id==='5')return `https://www.gamestop.com/search/?q=${q}`;if(id==='6')return `https://www.direct2drive.com/search?q=${q}`;return '#'}
function renderPopular(){const a=state.deals.slice(0,8);$('#popular').innerHTML=a.length?a.map((d,i)=>`<article class="card" data-id="${d.gameID}"><img class="thumb" src="${d.thumb}" alt=""><div class="cardBody"><div class="title">${esc(d.title)}</div><div class="price">${egp(d.salePrice)} <s>${egp(d.normalPrice)}</s></div><div class="discount">-${Math.round(d.savings||0)}% · #${i+1}</div></div></article>`).join(''):'<div class="muted">مفيش بيانات حالياً.</div>';document.querySelectorAll('.card').forEach(x=>x.onclick=()=>openGame(x.dataset.id))}
function renderDeals(){const a=state.deals.slice(0,18);$('#deals').innerHTML=a.length?a.map(d=>`<article class="deal"><img src="${d.thumb}" alt=""><div class="dealInfo"><div class="title">${esc(d.title)}</div><div class="store">${stores[d.storeID]||'Store'} · Deal rating ${Number(d.dealRating||0).toFixed(1)}</div></div><div class="dealRight"><div class="price">${egp(d.salePrice)}</div><div class="discount">-${Math.round(d.savings||0)}%</div><a class="store" href="${storeUrl(d)}" target="_blank" rel="noopener">شراء ↗</a></div></article>`).join(''):'<div class="muted">مفيش عروض حالياً.</div>'}
function renderSoftware(){$('#software').innerHTML=software.map(x=>`<div class="soft"><b>${x[0]}</b><span>${x[1]}</span><br><a href="${x[2]}" target="_blank" rel="noopener">الصفحة الرسمية ↗</a></div>`).join('')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function json(url){const r=await fetch(url);if(!r.ok)throw Error(r.status);return r.json()}
async function load(){try{const fx=await fetch('https://open.er-api.com/v6/latest/USD').then(r=>r.json());if(fx?.rates?.EGP)state.fx=fx.rates.EGP}catch{};try{const j=await json(`/api/deals?pageSize=60&sortBy=${state.sort}&desc=0`);state.deals=j.deals||[];$('#status').textContent=`آخر تحديث: ${new Date(j.updatedAt).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'})}`}catch(e){$('#status').textContent='تعذر تحديث البيانات';}renderPopular();renderDeals()}
async function openGame(id){$('#modal').classList.remove('hidden');$('#modalContent').innerHTML='<h2>جاري تحميل اللعبة...</h2>';try{const j=await json(`/api/game?id=${encodeURIComponent(id)}`);const g=j.game||{};const deals=g.deals||[];$('#modalContent').innerHTML=`<h2>${esc(g.info?.title||'Game')}</h2><p class="muted">قارن العروض المتاحة حالياً</p>${deals.length?deals.map(d=>`<div class="offer"><div><b>${stores[d.storeID]||'Store'}</b><div class="price">${egp(d.salePrice)}</div><span class="muted">${Math.round(d.savings||0)}% خصم</span></div><a href="${storeUrl({...d,title:g.info?.title,steamAppID:g.info?.steamAppID})}" target="_blank" rel="noopener">شراء</a></div>`).join(''):'<p>لا توجد عروض متاحة حالياً.</p>'}`}catch{$('#modalContent').innerHTML='<h2>حصل خطأ</h2><p class="muted">جرب تاني بعد لحظات.</p>'}}
let timer;$('#search').addEventListener('input',async e=>{clearTimeout(timer);const q=e.target.value.trim();if(q.length<2){$('#suggestions').style.display='none';return}timer=setTimeout(async()=>{try{const j=await json(`/api/search?title=${encodeURIComponent(q)}`);$('#suggestions').innerHTML=(j.results||[]).slice(0,7).map(x=>`<div class="suggest" data-id="${x.gameID}">${esc(x.external||x.name||'')}</div>`).join('')||'<div class="suggest">مفيش نتائج</div>';$('#suggestions').style.display='block';document.querySelectorAll('.suggest[data-id]').forEach(x=>x.onclick=()=>{openGame(x.dataset.id);$('#suggestions').style.display='none';$('#search').value=''})}catch{}},350)});
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.sort=b.dataset.sort;load()});$('#refresh').onclick=load;$('#menuBtn').onclick=()=>$('#drawer').classList.remove('hidden');$('#closeDrawer').onclick=()=>$('#drawer').classList.add('hidden');$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#accountBtn').onclick=()=>alert('الحساب والـ Google Login هنضيفهم بعد تثبيت الـ Data Engine والواجهة الأساسية.');$('#accountDrawer').onclick=()=>alert('الحساب هنربطه بـ Supabase في المرحلة القادمة.');$('#favBtn').onclick=()=>alert('المفضلة هتكون Local أولاً ثم Cloud مع الحساب.');$('#platformBtn').onclick=()=>alert('PC هو المصدر الحي الحالي. Xbox / PlayStation / Switch هنضيفهم بمصادر مسموحة لاحقاً.');$('#alertsBtn').onclick=()=>alert('تنبيهات السعر هتشتغل بعد إضافة قاعدة البيانات والـ scheduler.');renderSoftware();load();
