-- Lumen Price Radar — Supabase schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.wishlists (
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  title text,
  thumb text,
  steam_app_id text,
  created_at timestamptz not null default now(),
  primary key (user_id, game_id)
);

create table if not exists public.price_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  title text,
  target_egp numeric(12,2) not null check (target_egp > 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  triggered_at timestamptz
);

alter table public.profiles enable row level security;
alter table public.wishlists enable row level security;
alter table public.price_alerts enable row level security;

create policy "profiles own row" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "wishlist own rows" on public.wishlists for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "alerts own rows" on public.price_alerts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    new.raw_user_meta_data->>'avatar_url'
  ) on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
